name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configurar Node.js y habilitar la caché de dependencias
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar dependencias
      - run: npm ci --legacy-peer-deps

      # 4. Ejecutar Nx directamente, sin Nx Cloud
      # Nx Affected ejecuta solo las tareas afectadas por los cambios en el commit o PR.
      - run: npx nx affected --target=lint --target=test --target=build --target=e2e-ci
