name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio con todas las ramas
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master # Asegura que la rama master (main en algunos repositorios) se descargue

      # 2. Configurar Node.js y habilitar la caché de dependencias
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar dependencias
      - run: npm ci --legacy-peer-deps

      # 4. Ejecutar Nx con una base explícita
      # Compara los cambios entre la rama principal (master) y el commit actual (HEAD)
      - run: npx nx affected --base=origin/master --head=HEAD --target=lint --target=test --target=build --target=e2e-ci
